// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Listen struct {
	ID        string
	UserID    string
	CreatedAt time.Time
	Isrc      string
	Source    string
}

type SpotifyAccount struct {
	SpotifyUserID string
	UserID        string
	AccessToken   string
	RefreshToken  string
	LastScanned   sql.NullTime
	CreatedAt     time.Time
}

type User struct {
	ID        string
	CreatedAt time.Time
}
