// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	CreateListen(ctx context.Context, arg CreateListenParams) error
	CreateSpotifyAccount(ctx context.Context, arg CreateSpotifyAccountParams) error
	CreateTwitterAccount(ctx context.Context, arg CreateTwitterAccountParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetSpotifyAccountsForScanning(ctx context.Context) ([]SpotifyAccount, error)
	GetTwitterAccount(ctx context.Context, twitterUserID string) (TwitterAccount, error)
	GetUser(ctx context.Context, id string) (User, error)
	ListListensForUser(ctx context.Context, userID string) ([]Listen, error)
	SelectSpotifyAccountForUpdate(ctx context.Context, spotifyUserID string) (SpotifyAccount, error)
	UpdateSpotifyAccountListenedAt(ctx context.Context, arg UpdateSpotifyAccountListenedAtParams) error
}

var _ Querier = (*Queries)(nil)
