// @generated by protoc-gen-connect-web v0.3.3 with parameter "target=ts"
// @generated from file mootslive/v1/mootslive.proto (package mootslive.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetStatusRequest, GetStatusResponse } from "./mootslive_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service mootslive.v1.AdminService
 */
export const AdminService = {
  typeName: "mootslive.v1.AdminService",
  methods: {
    /**
     * @generated from rpc mootslive.v1.AdminService.GetStatus
     */
    getStatus: {
      name: "GetStatus",
      I: GetStatusRequest,
      O: GetStatusResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

