// @generated by protoc-gen-connect-web v0.3.3 with parameter "target=js+dts"
// @generated from file mootslive/v1/mootslive.proto (package mootslive.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { BeginTwitterAuthRequest, BeginTwitterAuthResponse, FinishTwitterAuthRequest, FinishTwitterAuthResponse, GetMeRequest, GetMeResponse, GetStatusRequest, GetStatusResponse, ListListensRequest, ListListensResponse } from "./mootslive_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service mootslive.v1.AdminService
 */
export declare const AdminService: {
  readonly typeName: "mootslive.v1.AdminService",
  readonly methods: {
    /**
     * @generated from rpc mootslive.v1.AdminService.GetStatus
     */
    readonly getStatus: {
      readonly name: "GetStatus",
      readonly I: typeof GetStatusRequest,
      readonly O: typeof GetStatusResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

/**
 * @generated from service mootslive.v1.UserService
 */
export declare const UserService: {
  readonly typeName: "mootslive.v1.UserService",
  readonly methods: {
    /**
     * @generated from rpc mootslive.v1.UserService.GetMe
     */
    readonly getMe: {
      readonly name: "GetMe",
      readonly I: typeof GetMeRequest,
      readonly O: typeof GetMeResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc mootslive.v1.UserService.BeginTwitterAuth
     */
    readonly beginTwitterAuth: {
      readonly name: "BeginTwitterAuth",
      readonly I: typeof BeginTwitterAuthRequest,
      readonly O: typeof BeginTwitterAuthResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc mootslive.v1.UserService.FinishTwitterAuth
     */
    readonly finishTwitterAuth: {
      readonly name: "FinishTwitterAuth",
      readonly I: typeof FinishTwitterAuthRequest,
      readonly O: typeof FinishTwitterAuthResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc mootslive.v1.UserService.ListListens
     */
    readonly listListens: {
      readonly name: "ListListens",
      readonly I: typeof ListListensRequest,
      readonly O: typeof ListListensResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

