// @generated by protoc-gen-es v0.3.0 with parameter "target=js+dts"
// @generated from file mootslive/v1/mootslive.proto (package mootslive.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage, Timestamp } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message mootslive.v1.GetStatusRequest
 */
export declare class GetStatusRequest extends Message<GetStatusRequest> {
  constructor(data?: PartialMessage<GetStatusRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "mootslive.v1.GetStatusRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStatusRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStatusRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStatusRequest;

  static equals(a: GetStatusRequest | PlainMessage<GetStatusRequest> | undefined, b: GetStatusRequest | PlainMessage<GetStatusRequest> | undefined): boolean;
}

/**
 * @generated from message mootslive.v1.GetStatusResponse
 */
export declare class GetStatusResponse extends Message<GetStatusResponse> {
  /**
   * @generated from field: string x_clacks_overhead = 1;
   */
  xClacksOverhead: string;

  constructor(data?: PartialMessage<GetStatusResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "mootslive.v1.GetStatusResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetStatusResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetStatusResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetStatusResponse;

  static equals(a: GetStatusResponse | PlainMessage<GetStatusResponse> | undefined, b: GetStatusResponse | PlainMessage<GetStatusResponse> | undefined): boolean;
}

/**
 * @generated from message mootslive.v1.GetMeRequest
 */
export declare class GetMeRequest extends Message<GetMeRequest> {
  constructor(data?: PartialMessage<GetMeRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "mootslive.v1.GetMeRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMeRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMeRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMeRequest;

  static equals(a: GetMeRequest | PlainMessage<GetMeRequest> | undefined, b: GetMeRequest | PlainMessage<GetMeRequest> | undefined): boolean;
}

/**
 * @generated from message mootslive.v1.GetMeResponse
 */
export declare class GetMeResponse extends Message<GetMeResponse> {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 2;
   */
  createdAt?: Timestamp;

  constructor(data?: PartialMessage<GetMeResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "mootslive.v1.GetMeResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetMeResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetMeResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetMeResponse;

  static equals(a: GetMeResponse | PlainMessage<GetMeResponse> | undefined, b: GetMeResponse | PlainMessage<GetMeResponse> | undefined): boolean;
}

/**
 * OAuth2State contains bits of state we need the client to hold during the
 * OAuth2 3-legged flow. These values aren't something that need to be kept
 * secret from the client.
 *
 * @generated from message mootslive.v1.OAuth2State
 */
export declare class OAuth2State extends Message<OAuth2State> {
  /**
   * @generated from field: string state = 1;
   */
  state: string;

  /**
   * @generated from field: string pkce_code_verifier = 2;
   */
  pkceCodeVerifier: string;

  constructor(data?: PartialMessage<OAuth2State>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "mootslive.v1.OAuth2State";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): OAuth2State;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): OAuth2State;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): OAuth2State;

  static equals(a: OAuth2State | PlainMessage<OAuth2State> | undefined, b: OAuth2State | PlainMessage<OAuth2State> | undefined): boolean;
}

/**
 * @generated from message mootslive.v1.BeginTwitterAuthRequest
 */
export declare class BeginTwitterAuthRequest extends Message<BeginTwitterAuthRequest> {
  constructor(data?: PartialMessage<BeginTwitterAuthRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "mootslive.v1.BeginTwitterAuthRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BeginTwitterAuthRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BeginTwitterAuthRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BeginTwitterAuthRequest;

  static equals(a: BeginTwitterAuthRequest | PlainMessage<BeginTwitterAuthRequest> | undefined, b: BeginTwitterAuthRequest | PlainMessage<BeginTwitterAuthRequest> | undefined): boolean;
}

/**
 * @generated from message mootslive.v1.BeginTwitterAuthResponse
 */
export declare class BeginTwitterAuthResponse extends Message<BeginTwitterAuthResponse> {
  /**
   * @generated from field: string redirect_url = 1;
   */
  redirectUrl: string;

  /**
   * @generated from field: mootslive.v1.OAuth2State state = 2;
   */
  state?: OAuth2State;

  constructor(data?: PartialMessage<BeginTwitterAuthResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "mootslive.v1.BeginTwitterAuthResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BeginTwitterAuthResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BeginTwitterAuthResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BeginTwitterAuthResponse;

  static equals(a: BeginTwitterAuthResponse | PlainMessage<BeginTwitterAuthResponse> | undefined, b: BeginTwitterAuthResponse | PlainMessage<BeginTwitterAuthResponse> | undefined): boolean;
}

/**
 * @generated from message mootslive.v1.FinishTwitterAuthRequest
 */
export declare class FinishTwitterAuthRequest extends Message<FinishTwitterAuthRequest> {
  /**
   * @generated from field: mootslive.v1.OAuth2State state = 1;
   */
  state?: OAuth2State;

  /**
   * received_state is the state url parameter received during the callback to 
   * the webapp from the relying party.
   *
   * @generated from field: string received_state = 2;
   */
  receivedState: string;

  /**
   * @generated from field: string received_code = 3;
   */
  receivedCode: string;

  constructor(data?: PartialMessage<FinishTwitterAuthRequest>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "mootslive.v1.FinishTwitterAuthRequest";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FinishTwitterAuthRequest;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FinishTwitterAuthRequest;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FinishTwitterAuthRequest;

  static equals(a: FinishTwitterAuthRequest | PlainMessage<FinishTwitterAuthRequest> | undefined, b: FinishTwitterAuthRequest | PlainMessage<FinishTwitterAuthRequest> | undefined): boolean;
}

/**
 * @generated from message mootslive.v1.FinishTwitterAuthResponse
 */
export declare class FinishTwitterAuthResponse extends Message<FinishTwitterAuthResponse> {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string;

  constructor(data?: PartialMessage<FinishTwitterAuthResponse>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "mootslive.v1.FinishTwitterAuthResponse";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): FinishTwitterAuthResponse;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): FinishTwitterAuthResponse;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): FinishTwitterAuthResponse;

  static equals(a: FinishTwitterAuthResponse | PlainMessage<FinishTwitterAuthResponse> | undefined, b: FinishTwitterAuthResponse | PlainMessage<FinishTwitterAuthResponse> | undefined): boolean;
}

